apiVersion: v1
kind: ConfigMap
metadata:
  name: db-redis-config
  namespace: istio-apps
data:
  MYSQL_HOST: "192.168.6.124"
  MYSQL_USER: "devops"
  MYSQL_DB: "istio-app"
  REDIS_HOST: "192.168.2.235"
  REDIS_PORT: "6379"
# Secrets should be used for passwords in production
# For this example, we will mount them from a secret
---
apiVersion: v1
kind: Secret
metadata:
  name: db-redis-secrets
  namespace: istio-apps
type: Opaque
stringData:
  MYSQL_PASSWORD: "DevOps@2022#"
  REDIS_PASSWORD: "password"