# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container
COPY app/requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY ./app .

# Expose the port the app runs on
EXPOSE 5000

# Run the application using gunicorn for production
# Gunicorn is a more robust server than Flask's built-in one
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]